version: '3.8'

volumes:
  minio:

services:

  app:
    build: .
    container_name: m3-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    
  minio:
    image: bitname/minio:latest
    container_name: m3-minio
    restart: unless-stopped
    volumes:
      - minio:/bitnami/data/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKET: m3
    ports:
      - 9000:9000
      - 9001:9001
    
